@startuml StandardWeaponLogic
state "StandardWeaponLogic State" as EternalJourney_Weapon_Abstract_State_StandardWeaponLogic_State {
  state "Idle" as EternalJourney_Weapon_Abstract_State_StandardWeaponLogic_State_Idle
  state "Attack" as EternalJourney_Weapon_Abstract_State_StandardWeaponLogic_State_Attack
}

EternalJourney_Weapon_Abstract_State_StandardWeaponLogic_State_Attack --> EternalJourney_Weapon_Abstract_State_StandardWeaponLogic_State_Idle : StartIdle
EternalJourney_Weapon_Abstract_State_StandardWeaponLogic_State_Idle --> EternalJourney_Weapon_Abstract_State_StandardWeaponLogic_State_Attack : StartAttack

EternalJourney_Weapon_Abstract_State_StandardWeaponLogic_State_Attack : OnEnter → Attacking
EternalJourney_Weapon_Abstract_State_StandardWeaponLogic_State_Idle : OnEnter → Idling

[*] --> EternalJourney_Weapon_Abstract_State_StandardWeaponLogic_State_Idle
@enduml