@startuml EnemyLogic
state "EnemyLogic State" as EternalJourney_Enemy_EnemyLogic_State {
  state "SpawnWaiting" as EternalJourney_Enemy_EnemyLogic_State_SpawnWaiting
  state "Closing" as EternalJourney_Enemy_EnemyLogic_State_Closing
  state "Destroy" as EternalJourney_Enemy_EnemyLogic_State_Destroy
}

EternalJourney_Enemy_EnemyLogic_State_Closing --> EternalJourney_Enemy_EnemyLogic_State_Destroy : TakeDamage
EternalJourney_Enemy_EnemyLogic_State_Destroy --> EternalJourney_Enemy_EnemyLogic_State_SpawnWaiting : TakeDamage
EternalJourney_Enemy_EnemyLogic_State_SpawnWaiting --> EternalJourney_Enemy_EnemyLogic_State_Closing : TargetDiscover

EternalJourney_Enemy_EnemyLogic_State_Closing : OnEnter → StartClose
EternalJourney_Enemy_EnemyLogic_State_Destroy : OnEnter → Damaged
EternalJourney_Enemy_EnemyLogic_State_SpawnWaiting : OnEnter → SpawnEnable

[*] --> EternalJourney_Enemy_EnemyLogic_State_SpawnWaiting
@enduml