@startuml StandardEnemyLogic
state "StandardEnemyLogic State" as EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State {
  state "SpawnWait" as EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_SpawnWait
  state "Invading" as EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Invading
}

EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Invading --> EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_SpawnWait : OutOfArea
EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_SpawnWait --> EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Invading : Spawn

EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Invading : CheckUnderZeroDurability() → Destroyed
EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Invading : OnBulletHit → CurrentDurChange
EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Invading : OnOutOfArea → Destroyed
EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Invading : OnPhysicsProcess → Move
EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Invading : UpdateColor() → UpdateColor
EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_SpawnWait : OnSpawn → StartInvade

[*] --> EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_SpawnWait
@enduml