@startuml StandardEnemyLogic
state "StandardEnemyLogic State" as EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State {
  state "SpawnWait" as EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_SpawnWait
  state "Invading" as EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Invading
}

EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Invading --> EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Invading : BulletHit
EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Invading --> EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Invading : PhysicsProcess
EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Invading --> EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_SpawnWait : BulletHit
EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Invading --> EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_SpawnWait : OutOfArea
EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_SpawnWait --> EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Invading : Spawn

EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Invading : OnBulletHit → Destroyed
EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Invading : OnOutOfArea → Destroyed
EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Invading : OnPhysicsProcess → Move

[*] --> EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_SpawnWait
@enduml