@startuml StandardEnemyLogic
state "StandardEnemyLogic State" as EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State {
  state "SpawnWaiting" as EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_SpawnWaiting
  state "Closing" as EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Closing
  state "TakingDamage" as EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_TakingDamage
  state "Destroy" as EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Destroy
}

EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Closing --> EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Destroy : OutOfArea
EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Closing --> EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_TakingDamage : TakeDamage
EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Destroy --> EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_SpawnWaiting : Removed
EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_SpawnWaiting --> EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Closing : TargetDiscover
EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_TakingDamage --> EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Closing : Alive
EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_TakingDamage --> EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Destroy : Collapse

EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Closing : OnEnter → StartClose
EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_Destroy : OnEnter → Disappear
EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_SpawnWaiting : OnEnter → SpawnEnable
EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_TakingDamage : OnEnter → Decay

[*] --> EternalJourney_Enemy_Abstract_State_StandardEnemyLogic_State_SpawnWaiting
@enduml