@startuml StatusUpSkillLogic
state "StatusUpSkillLogic State" as EternalJourney_Skills_StatusUp_State_StatusUpSkillLogic_State {
  state "InActive" as EternalJourney_Skills_StatusUp_State_StatusUpSkillLogic_State_InActive
  state "Active" as EternalJourney_Skills_StatusUp_State_StatusUpSkillLogic_State_Active
}

EternalJourney_Skills_StatusUp_State_StatusUpSkillLogic_State_Active --> EternalJourney_Skills_StatusUp_State_StatusUpSkillLogic_State_Active : Apply
EternalJourney_Skills_StatusUp_State_StatusUpSkillLogic_State_Active --> EternalJourney_Skills_StatusUp_State_StatusUpSkillLogic_State_Active : Remove
EternalJourney_Skills_StatusUp_State_StatusUpSkillLogic_State_Active --> EternalJourney_Skills_StatusUp_State_StatusUpSkillLogic_State_InActive : Remove
EternalJourney_Skills_StatusUp_State_StatusUpSkillLogic_State_InActive --> EternalJourney_Skills_StatusUp_State_StatusUpSkillLogic_State_Active : Apply

EternalJourney_Skills_StatusUp_State_StatusUpSkillLogic_State_Active : OnApply → Activated
EternalJourney_Skills_StatusUp_State_StatusUpSkillLogic_State_Active : OnEnter → Activated
EternalJourney_Skills_StatusUp_State_StatusUpSkillLogic_State_Active : OnExit → Deactivated
EternalJourney_Skills_StatusUp_State_StatusUpSkillLogic_State_Active : OnRemove → Activated

[*] --> EternalJourney_Skills_StatusUp_State_StatusUpSkillLogic_State_InActive
@enduml