@startuml BulletLogic
state "BulletLogic State" as EternalJourney_App_State_BulletLogic_State {
  state "Loaded" as EternalJourney_App_State_BulletLogic_State_Loaded
  state "InFlight" as EternalJourney_App_State_BulletLogic_State_InFlight
  state "Hitting" as EternalJourney_App_State_BulletLogic_State_Hitting
  state "Destroy" as EternalJourney_App_State_BulletLogic_State_Destroy
}

EternalJourney_App_State_BulletLogic_State_Destroy --> EternalJourney_App_State_BulletLogic_State_Loaded : Reload
EternalJourney_App_State_BulletLogic_State_Hitting --> EternalJourney_App_State_BulletLogic_State_Destroy : Collapse
EternalJourney_App_State_BulletLogic_State_Hitting --> EternalJourney_App_State_BulletLogic_State_InFlight : Penetrate
EternalJourney_App_State_BulletLogic_State_InFlight --> EternalJourney_App_State_BulletLogic_State_Hitting : Hit
EternalJourney_App_State_BulletLogic_State_Loaded --> EternalJourney_App_State_BulletLogic_State_InFlight : Fire

EternalJourney_App_State_BulletLogic_State_Destroy : OnEnter → Disappear
EternalJourney_App_State_BulletLogic_State_Hitting : OnEnter → Decay

[*] --> EternalJourney_App_State_BulletLogic_State_Loaded
@enduml