@startuml RegenSkillLogic
state "RegenSkillLogic State" as EternalJourney_RegenSkill_State_RegenSkillLogic_State {
  state "InActive" as EternalJourney_RegenSkill_State_RegenSkillLogic_State_InActive
  state "Active" as EternalJourney_RegenSkill_State_RegenSkillLogic_State_Active
}

EternalJourney_RegenSkill_State_RegenSkillLogic_State_Active --> EternalJourney_RegenSkill_State_RegenSkillLogic_State_Active : Apply
EternalJourney_RegenSkill_State_RegenSkillLogic_State_Active --> EternalJourney_RegenSkill_State_RegenSkillLogic_State_Active : Remove
EternalJourney_RegenSkill_State_RegenSkillLogic_State_Active --> EternalJourney_RegenSkill_State_RegenSkillLogic_State_Active : Tick
EternalJourney_RegenSkill_State_RegenSkillLogic_State_Active --> EternalJourney_RegenSkill_State_RegenSkillLogic_State_InActive : Remove
EternalJourney_RegenSkill_State_RegenSkillLogic_State_InActive --> EternalJourney_RegenSkill_State_RegenSkillLogic_State_Active : Apply

EternalJourney_RegenSkill_State_RegenSkillLogic_State_Active : OnApply → Activated
EternalJourney_RegenSkill_State_RegenSkillLogic_State_Active : OnEnter → Activated
EternalJourney_RegenSkill_State_RegenSkillLogic_State_Active : OnExit → Deactivated
EternalJourney_RegenSkill_State_RegenSkillLogic_State_Active : OnTick → TikHeal

[*] --> EternalJourney_RegenSkill_State_RegenSkillLogic_State_InActive
@enduml