@startuml StandardBulletFactoryLogic
state "StandardBulletFactoryLogic State" as EternalJourney_BulletFactory_State_StandardBulletFactoryLogic_State {
  state "ShootReady" as EternalJourney_BulletFactory_State_StandardBulletFactoryLogic_State_ShootReady
  state "Generate" as EternalJourney_BulletFactory_State_StandardBulletFactoryLogic_State_Generate
  state "CoolDown" as EternalJourney_BulletFactory_State_StandardBulletFactoryLogic_State_CoolDown
}

EternalJourney_BulletFactory_State_StandardBulletFactoryLogic_State_CoolDown --> EternalJourney_BulletFactory_State_StandardBulletFactoryLogic_State_ShootReady : CoolDownComplete
EternalJourney_BulletFactory_State_StandardBulletFactoryLogic_State_Generate --> EternalJourney_BulletFactory_State_StandardBulletFactoryLogic_State_CoolDown : StartCoolDonw
EternalJourney_BulletFactory_State_StandardBulletFactoryLogic_State_ShootReady --> EternalJourney_BulletFactory_State_StandardBulletFactoryLogic_State_Generate : Fire

EternalJourney_BulletFactory_State_StandardBulletFactoryLogic_State_CoolDown : OnEnter → Cooling
EternalJourney_BulletFactory_State_StandardBulletFactoryLogic_State_Generate : OnEnter → Generated

[*] --> EternalJourney_BulletFactory_State_StandardBulletFactoryLogic_State_ShootReady
@enduml