@startuml LightSwitchLogic
state "LightSwitchLogic State" as EternalJourney_AutoConnectTest_State_LightSwitchLogic_State {
  state "PoweredOn" as EternalJourney_AutoConnectTest_State_LightSwitchLogic_State_PoweredOn
  state "PoweredOff" as EternalJourney_AutoConnectTest_State_LightSwitchLogic_State_PoweredOff
}

EternalJourney_AutoConnectTest_State_LightSwitchLogic_State_PoweredOff --> EternalJourney_AutoConnectTest_State_LightSwitchLogic_State_PoweredOn : Toggle
EternalJourney_AutoConnectTest_State_LightSwitchLogic_State_PoweredOn --> EternalJourney_AutoConnectTest_State_LightSwitchLogic_State_PoweredOff : Toggle

EternalJourney_AutoConnectTest_State_LightSwitchLogic_State_PoweredOff : OnEnter → StatusChanged
EternalJourney_AutoConnectTest_State_LightSwitchLogic_State_PoweredOn : OnEnter → StatusChanged

[*] --> EternalJourney_AutoConnectTest_State_LightSwitchLogic_State_PoweredOff
@enduml