@startuml BaseFactoryLogic
state "BaseFactoryLogic State" as EternalJourney_Common_BaseFactory_State_BaseFactoryLogic_State {
  state "Ready" as EternalJourney_Common_BaseFactory_State_BaseFactoryLogic_State_Ready
  state "Generating" as EternalJourney_Common_BaseFactory_State_BaseFactoryLogic_State_Generating
  state "CoolDown" as EternalJourney_Common_BaseFactory_State_BaseFactoryLogic_State_CoolDown
}

EternalJourney_Common_BaseFactory_State_BaseFactoryLogic_State_CoolDown --> EternalJourney_Common_BaseFactory_State_BaseFactoryLogic_State_Ready : CoolDownComplete
EternalJourney_Common_BaseFactory_State_BaseFactoryLogic_State_Generating --> EternalJourney_Common_BaseFactory_State_BaseFactoryLogic_State_CoolDown : StartCoolDown
EternalJourney_Common_BaseFactory_State_BaseFactoryLogic_State_Ready --> EternalJourney_Common_BaseFactory_State_BaseFactoryLogic_State_Generating : Generate

EternalJourney_Common_BaseFactory_State_BaseFactoryLogic_State_CoolDown : OnEnter → Cooling
EternalJourney_Common_BaseFactory_State_BaseFactoryLogic_State_Generating : OnEnter → Generated

[*] --> EternalJourney_Common_BaseFactory_State_BaseFactoryLogic_State_Ready
@enduml