@startuml StandardBulletLogic
state "StandardBulletLogic State" as EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State {
  state "EmitWait" as EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_EmitWait
  state "InFlight" as EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_InFlight
}

EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_EmitWait --> EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_InFlight : Emit
EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_InFlight --> EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_EmitWait : Miss

EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_InFlight : CheckUnderZeroDurability() → Collapse
EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_InFlight : OnEnemyHit → CurrentDurChange
EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_InFlight : OnMiss → Collapse
EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_InFlight : OnPhysicsProcess → Move

[*] --> EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_EmitWait
@enduml