@startuml StandardBulletLogic
state "StandardBulletLogic State" as EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State {
  state "Loaded" as EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_Loaded
  state "InFlight" as EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_InFlight
  state "Hitting" as EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_Hitting
  state "Destroy" as EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_Destroy
}

EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_Destroy --> EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_Loaded : Reload
EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_Hitting --> EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_Destroy : Collapse
EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_Hitting --> EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_InFlight : Penetrate
EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_InFlight --> EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_Destroy : Miss
EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_InFlight --> EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_Hitting : Hit
EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_Loaded --> EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_InFlight : Fire

EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_Destroy : OnEnter → Disappear
EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_Hitting : OnEnter → Decay
EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_InFlight : OnEnter → Emitted

[*] --> EternalJourney_Bullet_Abstract_State_StandardBulletLogic_State_Loaded
@enduml