@startuml HealSkillLogic
state "HealSkillLogic State" as EternalJourney_HealSkill_State_HealSkillLogic_State {
  state "Ready" as EternalJourney_HealSkill_State_HealSkillLogic_State_Ready
}

EternalJourney_HealSkill_State_HealSkillLogic_State_Ready --> EternalJourney_HealSkill_State_HealSkillLogic_State_Ready : Apply

EternalJourney_HealSkill_State_HealSkillLogic_State_Ready : OnApply → Healed

[*] --> EternalJourney_HealSkill_State_HealSkillLogic_State_Ready
@enduml